version: 2
updates:
  # Monitor npm dependencies for security vulnerabilities
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  # Check daily for security updates
    open-pull-requests-limit: 10
    reviewers:
      - "rupesh43210"  # Your GitHub username
    assignees:
      - "rupesh43210"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Security updates take priority
    allow:
      - dependency-type: "all"
    # Enable security-only updates even without dependencies
    target-branch: "main"