version: 2
updates:
  # This project currently uses only Node.js built-in modules
  # Dependabot configuration is prepared for future use
  
  # Uncomment the npm section below when you add dependencies to package.json
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "09:00"
  #   open-pull-requests-limit: 10
  #   reviewers:
  #     - "rupesh"
  #   assignees:
  #     - "rupesh"
  #   commit-message:
  #     prefix: "chore"
  #     prefix-development: "chore"
  #     include: "scope"
  #   labels:
  #     - "dependencies"
  #     - "npm"
  #   target-branch: "main"

  # Uncomment the GitHub Actions section below when you add workflows
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "08:00"
  #   open-pull-requests-limit: 5
  #   rebase-strategy: "auto"
